### ISSUE TITLE
None of JS Functionality Working

### ISSUE THREAD

**Issue by Fludem** [htmlstreamofficial/preline#146] opened 2023-11-07 02:08 UTC
I'm using vite with laravel.

Downgrading to 1.9 and everything works, upgrading to 2.0 it all breaks.

No errors are displayed when building for production, and no console errors are displayed.

Both tooltips and drop down components are in use reflecting no JS interactivity.

I'm using the whole package not specific plugins.

**Comment by olegpix** [comment] 2023-11-07 10:28
Hello,
please provide more information. How did you update (via npm or just copied the folder).
Make sure your components have the appropriate CSS classes and markup.
Also make sure your js initializations are up to date with the new version.
I strongly recommend you compare your code with the current documentation.

**Comment by Hawksama** [comment] 2023-11-07 15:35
@olegpix, he is right. I've just updated to v2 using npm and the tabs and accordions are not working. Even though I copied a new example from preline's website, it's still not working.

**Comment by olegpix** [comment] 2023-11-07 15:47
> @olegpix, he is right. I've just updated to v2 using npm and the tabs and accordions are not working. Even though I copied a new example from preline's website, it's still not working.

Have you regenerated the Tailwind styles? Remember that plugins are based on Tailwind classes.
The styles need to be regenerated. You should also use the plugin.js file from Preline to regenerate styles correctly.

**Comment by Hawksama** [comment] 2023-11-07 15:50
Yes, regenerating the tailwind styles was the first thing I did. Where can I find the documentation on how to generate the styles from Preline plugin.js?

**Comment by olegpix** [comment] 2023-11-07 15:53
> Yes, regenerating the tailwind styles was the first thing I did. Where can I find the documentation on how to generate the styles from Preline plugin.js?

https://preline.co/docs/index.html

**Comment by Hawksama** [comment] 2023-11-07 15:55
Definitely, that's exactly what I did!

**Comment by olegpix** [comment] 2023-11-07 15:56
> Yes, regenerating the tailwind styles was the first thing I did. Where can I find the documentation on how to generate the styles from Preline plugin.js?

It will be helpful if you create a codesandbox project with some of your current pages to better understand each other.

**Comment by Hawksama** [comment] 2023-11-07 16:13
I am unable to get any sandbox with a Preline template to work.
For example: https://codesandbox.io/s/quizzical-breeze-r3tl9j?file=/fn-horizontal-tabs-with-icon-and-description.html
Or I'm doing something wrong within codesandbox.

**Comment by jahaganiev** [comment] 2023-11-07 17:26
The test [link](https://github.com/htmlstreamofficial/preline/issues/146#issuecomment-1799057044) doesn't contain the source code for testing. Closing for now until we will have proper source code with link for testing.

Meanwhile, please fee to open a new issue if you have other issues. Thanks!

**Comment by olegpix** [comment] 2023-11-07 17:29
> I am unable to get any sandbox with a Preline template to work. For example: https://codesandbox.io/s/quizzical-breeze-r3tl9j?file=/fn-horizontal-tabs-with-icon-and-description.html Or I'm doing something wrong within codesandbox.

The main thing I expect to see is the file structure of your project. Your Tailwind file. Tailwind configuration file. This may help us solve your problem. Sorry, but without it I can only imagine what the problem is.

<img width="273" alt="_05" src="https://github.com/htmlstreamofficial/preline/assets/20664129/f0b9f43a-84bc-45c5-a818-eddfca9fc725">

**Comment by Fludem** [comment] 2023-11-07 22:29
Hey @olegpix 

Tailwind Stuff:

```
    plugins: [
        require("preline/plugin"), require("@tailwindcss/forms"), require('flowbite/plugin')(
            {
                strategy: 'class', // only generate classes
            }
        ),
    ]
```

Content

```
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/**/*.blade.php',
        './resources/css/**/*.css',
        'node_modules/preline/dist/*.js',
        "./vendor/wireui/wireui/src/*.php",
        "./vendor/wireui/wireui/ts/**/*.ts",
        "./vendor/wireui/wireui/src/View/**/*.php",
        "./vendor/wireui/wireui/src/WireUi/**/*.php",
        "./vendor/wireui/wireui/src/resources/**/*.blade.php",
        './app/Http/Livewire/**/*Table.php',
        './vendor/wire-elements/pro/config/wire-elements-pro.php',
        './vendor/wire-elements/pro/**/*.blade.php',
        "./node_modules/flowbite/**/*.js",
    ],
```

And import ('preline') is in my app.js, which is being built and included in my laravel layout:

```@vite(['resources/css/app.css', 'resources/js/app.js'])```

Completely uninstalling preline and installing preline v1.9 and rebuilding it works, soon as I do this with V2 it doesn't anymore

**Comment by Fludem** [comment] 2023-11-07 22:36
@olegpix 

Not sure what I did but it seems to be working, I'm confused idk I'm also an idiot

**Comment by trumpetstech** [comment] 2023-11-08 10:52
Facing the same issue. I guess its related to typescript. As the main index file is index.d.ts which is a dynamic import and vite is having some issue including it.

**Comment by Ghostff** [comment] 2023-11-09 21:47
It seem like the overlay for example needs a button to work. 
https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/overlay/index.ts#L199
So while the constructor DOC show you can pass the modal instance, [it](https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/overlay/index.ts#L25) only accepts a button

**Comment by shanke-pvex** [comment] 2023-11-10 14:15
I use Laravel 10 Inertia Vue 3 Tailwind an Preline UI. I have the same problem - none of the javascript works with preline v2.0

**Comment by olegpix** [comment] 2023-11-10 15:48
> I use Laravel 10 Inertia Vue 3 Tailwind an Preline UI. I have the same problem - none of the javascript works with preline v2.0

Our teammate was testing Preline with Laravel. And he found an error in the documents
it should be ``import "preline";`` instead of ``import('preline')``. After that, he successfully launched Preline.
Please try connecting Preline in the same way.

**Comment by shanke-pvex** [comment] 2023-11-10 15:56
It works only on the first run with v.2.  If you go to another page and back all the javascript doesn't work.

**Comment by olegpix** [comment] 2023-11-10 16:18
> It works only on the first run with v.2. If you go to another page and back all the javascript doesn't work.

please check this ticket https://github.com/htmlstreamofficial/preline/issues/149#issuecomment-1805728611
It could be the same situation.
If yes, then you also need to initialize your components on the some lifecycle event.

**Comment by Fludem** [comment] 2023-11-10 23:32
> > It works only on the first run with v.2. If you go to another page and back all the javascript doesn't work.
> 
> please check this ticket [#149 (comment)](https://github.com/htmlstreamofficial/preline/issues/149#issuecomment-1805728611) It could be the same situation. If yes, then you also need to initialize your components on the some lifecycle event.

Hey,

Changing the import to import "preline"; works until you change component in livewire for me.

I then used the mentioned fix in the ticket, but what ends up happening is when I click on my dropdown it opens and closes quickly.

the 'hs-dropdown' element has the 'open' class but the dropdown content has the usual classes to make it visible, then it's removed and hidden is applied in quick succession.

**Comment by trumpetstech** [comment] 2023-11-11 13:52
This is still an issue in Laravel Livewire. Any update on how to resolve this?

**Comment by jahaganiev** [comment] 2023-11-29 23:39
Hey everyone,

Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) pages with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.

Cheers!

**Comment by kevinrkowalski** [comment] 2023-12-10 13:58
I'm having the same issue with my own project JS not working after upgrading to v2

**Comment by umaraziz0** [comment] 2023-12-19 05:05
I'm having the same problem as well. Running Laravel 10, Vue 3, Inertia.js v1

**Comment by MelvishNiz** [comment] 2023-12-20 07:20
Is there a new update? This issue has been around for more than 1 month

**Comment by jahaganiev** [comment] 2023-12-29 03:26
Closing the issue since it has been addressed with v2.x releases. If you are still having any issues, please open a new issue with more details with sources to debug.

For those migrating v1.9.x to v2.x - please take note that unfortunately, v2.0 comes with some breaking changes and you should make sure the scripts are implemented in the same way as v2.x documentation.

In addition, please check out some closed issues for workarounds, e.g. for Laravel Livewire #224 

Hope that helps!

**Closed by jahaganiev** 2023-12-29 03:26 UTC
