### ISSUE TITLE
Sidebar cannot be closed in "Sidebar & Header" example

### ISSUE THREAD

**Issue by agorgl** [htmlstreamofficial/preline#26] opened 2022-10-21 11:51 UTC
Viewing the examples from mobile,
In other sidebar examples, when the sidebar opens, a user can click outside the sidebar and the sidebar closes.
In the case of "Sidebar & Header" example the sidebar cannot be closed and the user needs to refresh the page

**Comment by m3skalina** [comment] 2022-11-21 10:12
Try to remove

line 407
`<div id='sidebar-backdrop' class='hidden transition duration fixed inset-0 z-[47] bg-gray-900 bg-opacity-50 dark:bg-opacity-80'></div>`

and change

line 160
`<div id="docs-sidebar" class="hs-sidebar hs-overlay-open:translate-x-0 -translate-x-full transition-all duration-300 transform hidden fixed top-0 left-0 bottom-0 z-[48] w-64 bg-white border-r border-gray-200 pt-7 pb-10 overflow-y-auto scrollbar-y lg:block lg:translate-x-0 lg:right-auto lg:bottom-0 dark:scrollbar-y dark:bg-gray-800 dark:border-gray-700" data-hs-overlay-backdrop-container='#sidebar-backdrop'>`

with 

`<div id="docs-sidebar" class="hs-sidebar hs-overlay-open:translate-x-0 -translate-x-full transition-all duration-300 transform hidden fixed top-0 left-0 bottom-0 z-[60] w-64 bg-white border-r border-gray-200 pt-7 pb-10 overflow-y-auto scrollbar-y lg:block lg:translate-x-0 lg:right-auto lg:bottom-0 dark:scrollbar-y dark:bg-gray-800 dark:border-gray-700"
    data-hs-overlay-backdrop-container='#sidebar-backdrop'
    > `

**Comment by Mr-Zafar** [comment] 2022-11-22 07:23
Hi, @agorgl and @m3skalina -

The issue is now fixed and live with updated code.

Thanks!

**Closed by Mr-Zafar** 2022-11-22 07:23 UTC
