### ISSUE TITLE
Doropdown broken: react vite

### ISSUE THREAD

**Issue by ashikck** [htmlstreamofficial/preline#170] opened 2023-11-22 05:52 UTC
Dropdown only appears with full page refresh. plz help

**Comment by lenart** [comment] 2023-11-26 21:30
Very likely a duplicate of https://github.com/htmlstreamofficial/preline/issues/171

**Comment by jahaganiev** [comment] 2023-11-27 22:57
Hey @ashikck - please check out #171 for the latest conversations and updates. Thanks!

**Closed by jahaganiev** 2023-11-27 22:57 UTC
