### ISSUE TITLE
PreLine latest version not working on NEXT 14

### ISSUE THREAD

**Issue by RobinGiel** [htmlstreamofficial/preline#180] opened 2023-11-25 18:18 UTC
Preline was working with version 1.9.0 on Next 14, after updating to latest version 2.0.2 nothing is working anymore.

**Comment by lenart** [comment] 2023-11-26 21:26
Very likely a duplicate of https://github.com/htmlstreamofficial/preline/issues/171

**Comment by jahaganiev** [comment] 2023-11-27 22:52
Hey @RobinGiel, our team recently updated Framework Guides for Next 14 with live playground demo, please have a look - https://preline.co/docs/frameworks-nextjs.html

Cheers!

**Closed by jahaganiev** 2023-11-27 22:52 UTC
