### ISSUE TITLE
Plugins stop working with SPA/Vue application

### ISSUE THREAD

**Issue by evici** [htmlstreamofficial/preline#163] opened 2023-11-14 14:11 UTC
### Discussed in https://github.com/htmlstreamofficial/preline/discussions/162

I did notice that since Preline v2.0.0 dropdowns (or realy any other JS functionality) stops working when navigating between app pages.

What happens:
1. I install Preline using documentation (tried different methods, different frameworks):
- https://preline.co/docs/frameworks-laravel.html
- https://preline.co/docs/frameworks-vuejs.html
- also tried with Nuxt and Splade, InertiaJS

Please note, that i have tried including <script src="./node_modules/preline/dist/preline.js"></script>

2. Applied "Navbar" from https://preline.co/examples/navigations-navbars.html and navbar works when using <a> links. However when using Vue/Nuxt/Splade/InertiaJS to have benefit of SPA i must use <Link> component to navigate between pages. So when i use <Link href="ANY_APP_ROUTE"> instead of <a> - on click dropdows stop working intil hard refresh (F5).
3. After hard refresh dropdown starts working again UNTIL i click on Link again - this means DOM rerender in SPA.

In v1.9.0 plugins work fine, but v2.0.0 has this issue.

https://github.com/htmlstreamofficial/preline/assets/44578107/71e5de16-2592-404d-b50e-c852a214d669

How do i solve this?

**Comment by warlisson** [comment] 2023-11-15 20:47
Same problem...

**Comment by lenart** [comment] 2023-11-26 21:33
Very likely a duplicate of https://github.com/htmlstreamofficial/preline/issues/171

**Comment by evici** [comment] 2023-11-26 21:36
> Very likely a duplicate of https://github.com/htmlstreamofficial/preline/issues/171

Very likely #171 is posted 7 days later than mine. Care to check?

**Comment by jahaganiev** [comment] 2023-11-27 22:49
Hey @evici - I've just posted an update to #171:

> Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) page with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.


Cheers!

**Comment by jahaganiev** [comment] 2023-11-29 23:08
Hey @evici - please let us know if you're still having the issue after our latest updates. Thanks!

**Comment by evici** [comment] 2023-11-30 02:44
Thanks for the update. Seems to work fine with this approach.

**Closed** 2023-11-30 02:44 UTC

**Comment by omar-shaheen** [comment] 2025-06-28 16:09
@evici Have you resolved the issue
