### ISSUE TITLE
Click on data-remove not firing any event on Advanced Select

### ISSUE THREAD

**Issue by jorgegonzalezpiedra** [htmlstreamofficial/preline#420] opened 2024-08-01 19:56 UTC
### Summary

When clicking the data-remove item "x" in advanced select the change event is not fired.

### Steps to Reproduce

1. Create a advanced select with multiple input
2. Add a "onChange" event with a console.log showing values
3. Select a a value, see hoe the console shows the log with the values
4. Click on the "x" to remove the item, see how the log shows nothing
[screen-capture (1).webm](https://github.com/user-attachments/assets/42c9416b-15c4-4155-b174-9cafb7d11291)

### Demo Link

[screen-capture (1).webm](https://github.com/user-attachments/assets/42c9416b-15c4-4155-b174-9cafb7d11291)

### Expected Behavior

When clicking "x" the item is removed

### Actual Behavior

When clicking "x" the item is NOT removed

### Screenshots

[When clicking "x" the item is removed][screen-capture (1).webm](https://github.com/user-attachments/assets/42c9416b-15c4-4155-b174-9cafb7d11291)

**Comment by oliverhaas** [comment] 2024-08-22 10:53
I can confirm that removing with the "x" is not firing the change event, since it is removed from the select via javascript, and javascript value updates do not trigger change events by default. However, the Advanced Select should behave like a normal select would imo, so I'm agreeing with you.

Your wording is not ideal however, since the selection actually is removed from the select. So if you submit a form, it works as expected.

A simple workaround is to just add an event listener on click and dispatch a change event yourself.

**Comment by olegpix** [comment] 2024-10-07 15:04
@jorgegonzalezpiedra Hi, 
Thank you for reporting this bug, we will fix it in the next update.

**Comment by jahaganiev** [comment] 2024-12-04 00:21
Hey everyone, the issue has been resolved in the latest v2.6.0 release. Thanks!

**Closed by jahaganiev** 2024-12-04 00:21 UTC
Labels: bug
