### ISSUE TITLE
Official Preline website (preline.co) is very bugy on the iphone safari.

### ISSUE THREAD

**Issue by tppope** [htmlstreamofficial/preline#108] opened 2023-07-25 18:01 UTC
Page is blank when scrolling through website.

**Comment by Mr-Zafar** [comment] 2023-08-07 05:17
Can you provide more details like iPhone and Safari versions? If possible, videos or screenshots of those blank pages and links.

**Comment by tppope** [comment] 2023-08-09 08:23
Safari version on mac and iPhone is 16.6.  

Videos: 

https://github.com/htmlstreamofficial/preline/assets/74919436/84faa2c2-81c9-4a76-8abb-fccfb2d08357

https://github.com/htmlstreamofficial/preline/assets/74919436/60270be7-efc5-4e40-a4f8-226bdc774fbc

**Comment by Mr-Zafar** [comment] 2023-08-09 14:59
@tppope Thanks for the videos. I found that the issue is with the .blur-* classes we are using on these cards. We will fix it soon.
<img width="1388" alt="Screenshot 2023-08-09 at 19 11 34" src="https://github.com/htmlstreamofficial/preline/assets/5662351/c9c82145-ae61-42b1-b741-52ac7d1a657f">

**Comment by Mr-Zafar** [comment] 2023-08-10 10:39
@tppope it's now fixed and closing this issue

**Closed by Mr-Zafar** 2023-08-10 10:39 UTC
Labels: enhancement

**Comment by tppope** [comment] 2023-08-10 11:04
Yes! It looks much better.
