### ISSUE TITLE
Components Needs a Page Refresh to work: Any idea?

### ISSUE THREAD

**Issue by abhayekanath** [htmlstreamofficial/preline#178] opened 2023-11-24 12:01 UTC
Hey, I'm running into issues with stuff like Advanced Select and Offcanvas in my Vite front-end. They depend on preline.js, and it's being a bit weird—everything's cool after a page refresh, though. Any thoughts on fixing this?

**Comment by lenart** [comment] 2023-11-26 21:27
Very likely a duplicate of https://github.com/htmlstreamofficial/preline/issues/171

**Comment by jahaganiev** [comment] 2023-11-27 22:55
Hey @abhayekanath - please check out for the latest conversations at #171 as Lenart mentioned.

**Closed by jahaganiev** 2023-11-27 22:55 UTC
